# Generated by Django 4.2.7 on 2023-12-03 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Name Recipe'),
        ),
    ]
