# Generated by Django 4.2.7 on 2023-12-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipedescription',
            options={'ordering': ('-weight',)},
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Название продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity_cooked',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Приготовлено блюд'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Название рецепта'),
        ),
        migrations.AlterField(
            model_name='recipedescription',
            name='weight',
            field=models.PositiveSmallIntegerField(verbose_name='Вес в граммах'),
        ),
    ]
