# Generated by Django 4.2.7 on 2023-12-03 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_remove_recipedescription_unique_recipe_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipedescription',
            options={'ordering': ('recipe_id',)},
        ),
        migrations.AlterField(
            model_name='recipedescription',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe'),
        ),
    ]
