# Generated by Django 4.2.7 on 2023-12-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_recipedescription_recipe'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='recipedescription',
            constraint=models.UniqueConstraint(fields=('product', 'recipe'), name='unique_recipe_description'),
        ),
    ]
