# Generated by Django 4.2.7 on 2023-12-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_recipedescription_unique_recipe_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Название продукта'),
        ),
    ]
