# Generated by Django 4.2.7 on 2023-12-05 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_product_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipedescription',
            options={},
        ),
    ]
